## Unrecoverable Errors with `panic!`
There are two ways to cause a panic in practice:
1. by taking an action that causes our code to panic (such as accessing an array past the end)
2. by explicitly calling the panic! macro

> #### Unwinding the Stack or Aborting in Response to a Panic
> By default, when a panic occurs, the program begins unwinding, which means Rust walks back up the stack and cleans up the data from each function it encounters. However, this walking back and cleanup is a lot of work. Rust, therefore, allows you to choose the alternative of immediately aborting, which ends the program without cleaning up.
> <br/><br/>Memory that the program was using will then need to be cleaned up by the operating system. If in your project you need to make the resulting binary as small as possible, you can switch from unwinding to aborting upon a panic by adding `panic = 'abort'` to the appropriate `[profile]` sections in your Cargo.toml file. For example, if you want to abort on panic in release mode, add this:
> ```
> [profile.release]
> panic = 'abort'
> ```

### Using a `panic!` Backtrace
A `panic!` call can come from a bug in our code. For example, let's try to access an index that is beyond the length of a vector:
```rust
fn main() {
    let v = vec![1, 2, 3];

    v[99];
}
```
calling `RUST_BACKTRACE=1 cargo run` on the above code produces:
```
$ RUST_BACKTRACE=1 cargo run
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 99', src/main.rs:4:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:84:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:242:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/vec/mod.rs:2591:9
   6: panic::main
             at ./src/main.rs:4:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
- In C, attempting to read beyond the end of a data structure is undefined behavior. Despite the memory not belonging to that data structure, doing the above could result in access to something else that is located at the address. This is called a ***buffer overread*** and it can lead to security vulnerabilities if an attacker is able to manipulate the index in such a way that enables them to read data they shouldnâ€™t be allowed to that is stored after the data structure.

A **backtrace** is a list of all the functions that have been called to get to this point.

### Quiz 1 Notes:
From question 2:
- What isn't a good reason to use a panic?:
    - The program has reached an error state which should be communicated to a caller function. A panic should not be used to communicate failure within the program. The default assumption is that caller functions will not try to catch panics.