## Recoverable Errors with `Result`

Recall from Chapter 2 that the `Result` enum is defined as having two variants, `Ok` and `Err`, as follows:
```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```
The `T` and `E` are generic type parameters: `T` represents the type of the value that will be returned in a success case within the `Ok` variant, and `E` represents the type of the error that will be returned in a failure case within the `Err` variant. Because `Result` has these generic type parameters, we can use the `Result` type and the functions defined on it in many different situations where the successful value and error value we want to return may differ.

### Matching on Different Errors
For example, handling a situation where a file is or isn't found when trying to open it:
```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => {
                panic!("Problem opening the file: {:?}", other_error);
            }
        },
    };
}
```
But this is a lot of matching, you can imagine this can get out of hand quickly. So we can use `unwrap_or_else()` instead with a ***closure*** to make it more readable:
```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file = File::open("hello.txt").unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt").unwrap_or_else(|error| {
                panic!("Problem creating the file: {:?}", error);
            })
        } else {
            panic!("Problem opening the file: {:?}", error);
        }
    });
}
```

### Quiz 1
1. Which of these statements best describes why `File::open` returns a `Result` and not an `Option`?
#### Answer:
Because `Result` can represent why an operation failed, and file opening can fail for many reasons. `Option` can just represent that an operation has failed, but `Result` can explain why the operation has failed.

### Propogating Errors
When a functionâ€™s implementation calls something that might fail, instead of handling the error within the function itself, you can return the error to the calling code so that it can decide what to do. This is known as *propagating the error* and it gives more control to the calling code, where there might be more information or logic that dictates how the error should be handled than what's available in the context of your code. The following shows this way of handling errors:
```rust
use std::fs::File;
use std::io::{self, Read};

fn main() {

fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");

    let mut username_file = match username_file_result {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut username = String::new();

    match username_file.read_to_string(&mut username) {
        Ok(_) => Ok(username),
        Err(e) => Err(e),
    }
}
}
```

### A Shortcut for Propogating Errors: the `?` Operator
The following is the shortcut way of writing the above example (using the `?` operator):
```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}
```
A `?` placed after some `Result` value works in nearly the same manners as a `match` that handles `Result` values (like in the previous example). If `Result` is an `Ok`, the value inside of it will be returned from the expression. If it's instead an `Err`, then it will be returned from the function as if we used the `return` keyword to propogate an error value.
- error values that have the `?` operator called on them go through the `from` function defined in the `From` trait in the standard library, which is used to convert values from one type into another. When the `?` operator calls the `from` function, the error type received is converted into the error type defined in the return type of the current function.
- we could change the `read_username_from_file` function to return a custom error type named `OurError` that we define. If we also define `impl From<io::Error>` for `OurError` to construct an instance of `OurError` from an `io::Error`, then the `?` operator calls in the body of `read_username_from_file` and that will call `from` and convert the error types without needing to add any more code to the function.

Here is are even more ergonomic ways of writing the previous `read_username_from_file()` functions:
```rust
use std::{
    fs::{self, File},
    io::{self, Read},
};

fn main() {}

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();
    File::open("hello.txt")?.read_to_string(&mut username)?;
    Ok(username)
}

/* or */

fn read_username_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt")
}
```

### Where The `?` Operator Can Be Used
The `?` operator can only be used when a function's return type aligns with the value that `?` is used on. This is because `?` performs an early return of a value of the function.

### Quiz 2
1. Given an arbitrary expression `e` of type `Result<T, E>`, which code snippet best represents how `e?` is translated?
#### Answer:
```rust
match e {
    Ok(x) => x,
    Err(err) => { return Err(err); }
}
```
If `e` is a `Result`, then `e?` extracts the value inside the `Ok` if possible, otherwise returning the `Err` out of the current function.

2. Determine whether the program will pass the compiler. If it passes, write the expected output of the program if it were executed.
```rust

// assume hello.txt has the contents "will"
fn read_username_from_file() -> Option<String> {
  let mut username_file = File::open("hello.txt")?;
  let mut username = String::new();
  username_file.read_to_string(&mut username)?;
  Some(username)
}
fn main() {
  println!("{}", read_username_from_file().unwrap()); 
}
```
#### Answer:
This program does not compile. `File::open` returns a `Result`, but the return type of `read_username_from_file` is an `Option`. So it's therefore invalid to use the `?` operator; that is, unless `Result` is converted to an `Option` (e.g. with the `Result::ok` method).